# Header

menu:
  主页: /
  git: /tags/git
  css: /tags/css

# SubNav
subnav:
  github: "https://github.com/bin248163"
  weibo: "http://weibo.com/u/5819460711"
  #rss: "#"
  zhihu: "#"
  qq: "http://wpa.qq.com/msgrd?v=3&uin=1047576335&site=dodocawebot&menu=yes"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /zfb.jpg
# 微信二维码图片地址
weixin: /wx.png

# Miscellaneous
baidu_analytics: '662c6e17f608df9e3ca0f00f1fd85ea8'
google_analytics: ''
favicon: /favicon.ico
#你的头像url
avatar: /1.png

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo: true

duoshuo: bin248163

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends: 
  home: http://www.qianxiaoduan.com
  github: https://github.com/bin248163
  taobao: https://shop151980538.taobao.com/?spm=a230r.7195193.1997079397.2.pEuJRi
  zhiwei: http://juelie123.coding.me

aboutme: 前小端<br> <br> 专注于前端开发

# Site
title: bin
subtitle: 闭关修炼ing~
description: 擅长各项前端技能，深入研究移动端开发与前端性能。 
author: bin
email: 1047576335@qq.com
keywords: "前小端,yzb123,web前端开发,前端框架,网站前端开发,HTML5教程,CSS3教程,前端性能优化,jquery教程,sass教程,js教程,前端工程师,wordpress教程,seo优化,个人博客网站,github教程"
